/* Generated By:JJTree: Do not edit this line. ASTArrayType.java */

public class ASTArrayType extends SimpleNode {
	ASTPrimitiveType primitiveType;
	ASTClassType classType;
	int dimensions = 0;
	String typeName = "";
	String elementTypeName;
	public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
