/* Generated By:JJTree: Do not edit this line. ASTAccessModifier.java */

public class ASTAccessModifier extends SimpleNode {
	int modifier; //fill by parser
	int accessModifier; //Convert to UCSYClasAttribute
  public ASTAccessModifier(int id) {
    super(id);
  }

  public ASTAccessModifier(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
