/* Generated By:JJTree: Do not edit this line. ASTArgumentsList.java */
import java.util.*;

public class ASTArgumentsList extends ParentExpression {
	ArrayList<ASTExpression> expressionList = new ArrayList<ASTExpression>();
	Method method;
  public ASTArgumentsList(int id) {
    super(id);
  }

  public ASTArgumentsList(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
