/* Generated By:JJTree: Do not edit this line. ASTAndNode.java */

public class ASTAndNode extends ParentExpression {
	ParentExpression opOne;
	ParentExpression opTwo;
  public ASTAndNode(int id) {
    super(id);
  }

  public ASTAndNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
