/* Generated By:JJTree: Do not edit this line. ASTArrayAllocation.java */

public class ASTArrayAllocation extends ParentExpression {
	ParentExpression arrayAllocationNode;
	
  public ASTArrayAllocation(int id) {
    super(id);
  }

  public ASTArrayAllocation(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
