/* Generated By:JJTree: Do not edit this line. ASTAssignmentStatementLookAhead.java */

public class ASTAssignmentStatementLookAhead extends SimpleNode {
  public ASTAssignmentStatementLookAhead(int id) {
    super(id);
  }

  public ASTAssignmentStatementLookAhead(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
