/* Generated By:JJTree: Do not edit this line. ASTArrayExpression.java */

public class ASTArrayExpression extends SimpleNode {
  public ASTArrayExpression(int id) {
    super(id);
  }

  public ASTArrayExpression(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
