/* Generated By:JJTree: Do not edit this line. ASTAbstractMethodDeclaration.java */

public class ASTAbstractMethodDeclaration extends MemberDeclaration {
	ASTReturnType returnType;
	ASTFormalParameters formalParameters;
	Token t;
	
	String abstractMethodName;
	String abstractMethodSignature;
	String abstractMethodReturnType;
	int modifier ;
	UCSYMethod abstractMethod;
	
  public ASTAbstractMethodDeclaration(int id) {
    super(id);
  }

  public ASTAbstractMethodDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
