/* Generated By:JJTree: Do not edit this line. ASTArgumentsSuffix.java */

public class ASTArgumentsSuffix extends ParentName {
	String parentClassName;
	String methodName;
	String methodSignature;
	ASTArguments arguments;
	Method method;
  public ASTArgumentsSuffix(int id) {
    super(id);
  }

  public ASTArgumentsSuffix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
