/* Generated By:JJTree: Do not edit this line. ASTAssignmentStatement.java */

public class ASTAssignmentStatement extends ParentStatement {
	String sourceType;
	String destinationType;
	ASTPrimaryExpression primaryExpression;
	ASTAssignmentOperator assignmentOperator;
	ASTExpression expression;
	
  public ASTAssignmentStatement(int id) {
    super(id);
  }

  public ASTAssignmentStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
