/* Generated By:JJTree: Do not edit this line. ASTBeforeCall.java */

public class ASTBeforeCall extends BeforeOrAfterClause {
	
	ASTMethodSignature methodSignature;
	ASTMethodCall      methodCall;
	UCSYMethod         method;	
  public ASTBeforeCall(int id) {
    super(id);
  }

  public ASTBeforeCall(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
