/* Generated By:JJTree: Do not edit this line. ASTBooleanLiteral.java */

public class ASTBooleanLiteral extends ParentExpression {
	Token t;
	boolean value;
  public ASTBooleanLiteral(int id) {
    super(id);
  }

  public ASTBooleanLiteral(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
