/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java */

public class ASTBreakStatement extends ParentStatement {
	Token t;
	Token label;
	String labelName;
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
