/* Generated By:JJTree: Do not edit this line. ASTBlock.java */
import java.util.*;

public class ASTBlock extends ParentStatement {

	ArrayList<ASTStatement>	 statementList = new ArrayList<ASTStatement>();
  public ASTBlock(int id) {
    super(id);
  }

  public ASTBlock(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
