/* Generated By:JJTree: Do not edit this line. ASTCaseExpression.java */

public class ASTCaseExpression extends ParentExpression {
	ASTIntegerLiteral integerLiteral;
	ASTCharLiteral charLiteral;
	ASTCaseIdentifier caseIdentifier;
	Object value;	
  public ASTCaseExpression(int id) {
    super(id);
  }

  public ASTCaseExpression(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
