/* Generated By:JJTree: Do not edit this line. ASTCaseIdentifier.java */

public class ASTCaseIdentifier extends ParentExpression {
	Token t;
	String idName;
  public ASTCaseIdentifier(int id) {
    super(id);
  }

  public ASTCaseIdentifier(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
