/* Generated By:JJTree: Do not edit this line. ASTCastExpression.java */

public class ASTCastExpression extends ParentExpression {
	ASTType type;
	ParentExpression expression;
	
	String castDestination;
	String castSource;
  public ASTCastExpression(int id) {
    super(id);
  }

  public ASTCastExpression(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
