/* Generated By:JJTree: Do not edit this line. ASTCastNode.java */

public class ASTCastNode extends ParentExpression {
	ParentExpression opOne;
  public ASTCastNode(int id) {
    super(id);
  }

  public ASTCastNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
