/* Generated By:JJTree: Do not edit this line. ASTClassModifier.java */

public class ASTClassModifier extends SimpleNode {
	
	int modifier;
  public ASTClassModifier(int id) {
    super(id);
  }

  public ASTClassModifier(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
