/* Generated By:JJTree: Do not edit this line. ASTCaseStatement.java */
import java.util.*;

public class ASTCaseStatement extends ParentExpression {
	Token t;
	ASTCaseExpression caseExpression;
	ArrayList<ASTStatement> statementList = new ArrayList<ASTStatement>();
	
	
	ASTExpression switchExpression;
	
	ASTSwitchStatement parentSwitch;
	int startOffest = -1;
  public ASTCaseStatement(int id) {
    super(id);
  }

  public ASTCaseStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
