/* Generated By:JJTree: Do not edit this line. ASTClassType.java */

public class ASTClassType extends SimpleNode {
	Token t;
	
	String classTypeName;
	
  public ASTClassType(int id) {
    super(id);
  }

  public ASTClassType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
