/* Generated By:JJTree: Do not edit this line. ASTConstructorDeclaration.java */

import java.util.*;

public class ASTConstructorDeclaration extends MemberDeclaration {
	Token t;
	UCSYMethod constructorMethod;
	boolean isStatic;
	int modifier;
	ASTMethodModifier methodModifier;
	ASTFormalParameters formalParameters;
	String constructorName;
	String constructorNameInByteCode;
	String constructorSignature;
	String constructorReturnType;
	
	String constructorProtocol;
	ASTExplicitConstructorCall explicitConstructorCall ;
	ArrayList<ASTStatement> statementList = new ArrayList<ASTStatement>();
	
  public ASTConstructorDeclaration(int id) {
    super(id);
  }

  public ASTConstructorDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
