/* Generated By:JJTree: Do not edit this line. ASTConformsClause.java */
import java.util.*;

public class ASTConformsClause extends SimpleNode {
	ArrayList<ASTIdentifier> conformsIdentifier = new ArrayList<ASTIdentifier>();
	
  public ASTConformsClause(int id) {
    super(id);
  }

  public ASTConformsClause(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
