/* Generated By:JJTree: Do not edit this line. ASTDoubleLiteral.java */

public class ASTDoubleLiteral extends ParentExpression {
	double value;
	Token t;
  public ASTDoubleLiteral(int id) {
    super(id);
  }

  public ASTDoubleLiteral(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
