/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java */

public class ASTDoStatement extends ParentStatement {
	ASTStatement statement;
	ASTExpression expression;
  public ASTDoStatement(int id) {
    super(id);
  }

  public ASTDoStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
