/* Generated By:JJTree: Do not edit this line. ASTDefaultStatement.java */
import java.util.*;

public class ASTDefaultStatement extends SimpleNode {
	ArrayList<ASTStatement> statementList = new ArrayList<ASTStatement>();
	
	ASTSwitchStatement parentSwitch = null;
	int startOffest = -1;
  public ASTDefaultStatement(int id) {
    super(id);
  }

  public ASTDefaultStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
