/* Generated By:JJTree: Do not edit this line. ASTDivsionNode.java */

public class ASTDivsionNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTDivsionNode(int id) {
    super(id);
  }

  public ASTDivsionNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
