/* Generated By:JJTree: Do not edit this line. ASTDimensionParameter.java */
import java.util.*;

public class ASTDimensionParameter extends SimpleNode {
	ArrayList<ASTExpression> expressionList = new ArrayList<ASTExpression>();
	
	int noOfDimension;
  public ASTDimensionParameter(int id) {
    super(id);
  }

  public ASTDimensionParameter(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
