/* Generated By:JJTree: Do not edit this line. ASTDelegateDeclaration.java */

public class ASTDelegateDeclaration extends MemberDeclaration {
	
	Token t;
	UCSYField delegateField;
	ASTType   type;
	String    delegateName;
	String    delegateTypeName;
	DelegateClause delegateClause;
	boolean   handleAll;
	boolean   forwardsClause;
	boolean   decorateClause;
	int modifier;
  public ASTDelegateDeclaration(int id) {
    super(id);
  }

  public ASTDelegateDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
