/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

public class ASTExpression extends ParentExpression {
	ParentExpression exp;
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
