/* Generated By:JJTree: Do not edit this line. ASTExplicitConstructorCall.java */

public class ASTExplicitConstructorCall extends SimpleNode {
	boolean thisCall ;
	boolean superCall;
	ASTArguments arguments;
	
  public ASTExplicitConstructorCall(int id) {
    super(id);
  }

  public ASTExplicitConstructorCall(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
