/* Generated By:JJTree: Do not edit this line. ASTFieldDeclaration.java */

public class ASTFieldDeclaration extends MemberDeclaration {
	Token t;
	ASTFunctorDeclaration functorDeclaration;
	ASTNormalFieldDeclaration normalFieldDeclaration;	
  public ASTFieldDeclaration(int id) {
    super(id);
  }

  public ASTFieldDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
