/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java */

public class ASTForUpdate extends SimpleNode {
	ASTAssignmentStatement assignmentStatement;
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
