/* Generated By:JJTree: Do not edit this line. ASTFormalParameter.java */

public class ASTFormalParameter extends SimpleNode {
	
	ASTType mainType;
	ASTType subType;
	ASTVariableDeclaratorId variableDeclaratorId;
	
	String typeName;
  public ASTFormalParameter(int id) {
    super(id);
  }

  public ASTFormalParameter(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
