/* Generated By:JJTree: Do not edit this line. ASTForwardsClause.java */
import java.util.*;

public class ASTForwardsClause extends DelegateClause {
	ArrayList<ASTSignatureToCall> signatureToCallList = new ArrayList<ASTSignatureToCall>();
  public ASTForwardsClause(int id) {
    super(id);
  }

  public ASTForwardsClause(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
