/* Generated By:JJTree: Do not edit this line. ASTFunctorDeclarationLookAhead.java */

public class ASTFunctorDeclarationLookAhead extends SimpleNode {
  public ASTFunctorDeclarationLookAhead(int id) {
    super(id);
  }

  public ASTFunctorDeclarationLookAhead(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
