/* Generated By:JJTree: Do not edit this line. ASTForExpression.java */

public class ASTForExpression extends SimpleNode {
	ASTExpression expression;
  public ASTForExpression(int id) {
    super(id);
  }

  public ASTForExpression(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
