/* Generated By:JJTree: Do not edit this line. ASTFreeClassDeclaration.java */

public class ASTFreeClassDeclaration extends ParentTypeDeclaration {
	ASTFreeClassHeader freeClassHeader;
	ASTFreeClassBody   freeClassBody;
	UCSYClass theFreeClass;	
  public ASTFreeClassDeclaration(int id) {
    super(id);
  }

  public ASTFreeClassDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
