/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java */
import java.util.*;

public class ASTFormalParameters extends SimpleNode {
	
	ArrayList<ASTFormalParameter> formalParameterList = new ArrayList<ASTFormalParameter>();
	String formalParameterListName;
	
  public ASTFormalParameters(int id) {
    super(id);
  }

  public ASTFormalParameters(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
