/* Generated By:JJTree: Do not edit this line. ASTFreeClassHeader.java */

public class ASTFreeClassHeader extends SimpleNode {
	Token freeClassToken;
	Token parentClassToken;
	String freeClassName;
	String parentClassName;
	
  public ASTFreeClassHeader(int id) {
    super(id);
  }

  public ASTFreeClassHeader(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
