/* Generated By:JJTree: Do not edit this line. ASTForInit.java */

public class ASTForInit extends SimpleNode {
	ASTLocalVariableDeclaration localVariableDeclaration;
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
