/* Generated By:JJTree: Do not edit this line. ASTFloatLiteral.java */

public class ASTFloatLiteral extends ParentExpression{
	Token t;
	double value;
  public ASTFloatLiteral(int id) {
    super(id);
  }

  public ASTFloatLiteral(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
