/* Generated By:JJTree: Do not edit this line. ASTForUpdator.java */

public class ASTForUpdator extends SimpleNode {
	ASTForUpdate forUpdate;
  public ASTForUpdator(int id) {
    super(id);
  }

  public ASTForUpdator(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
