/* Generated By:JJTree: Do not edit this line. ASTFunctorDeclaration.java */

public class ASTFunctorDeclaration extends ParentTypeDeclaration {
	int modifier;
	ASTReturnType returnType;
	ASTFormalParameters formalParameters;
	Token t;
	String functorName;
	String functorSignature;
	String functorReturnType;
	
	FunctorType functor;
  public ASTFunctorDeclaration(int id) {
    super(id);
  }

  public ASTFunctorDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
