/* Generated By:JJTree: Do not edit this line. ASTGTEqualNode.java */

public class ASTGTEqualNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTGTEqualNode(int id) {
    super(id);
  }

  public ASTGTEqualNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
