/* Generated By:JJTree: Do not edit this line. ASTHandleAllClause.java */
import java.util.*;

public class ASTHandleAllClause extends DelegateClause {
	ArrayList<Method> allPublicMethod;
	ArrayList<UCSYMethod> allMethod = new ArrayList<UCSYMethod>();
  public ASTHandleAllClause(int id) {
    super(id);
  }

  public ASTHandleAllClause(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
