/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java */

public class ASTIntegerLiteral extends ParentExpression{
	
	Token t;
	long value ;
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
