/* Generated By:JJTree: Do not edit this line. ASTInterfaceDeclaration.java */

public class ASTInterfaceDeclaration extends ParentTypeDeclaration {
	ASTInterfaceHeader interfaceHeader;
	ASTInterfaceBody   interfaceBody;
	
	UCSYInterface theInterface = new UCSYInterface();
  public ASTInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
