/* Generated By:JJTree: Do not edit this line. ASTInterfaceHeader.java */
import java.util.*;

public class ASTInterfaceHeader extends SimpleNode {
	Token t;
	String interfaceName;
	ArrayList<String> interfaceParentName = new ArrayList<String>();
  public ASTInterfaceHeader(int id) {
    super(id);
  }

  public ASTInterfaceHeader(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
