/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java */

public class ASTInstanceOfExpression extends ParentExpression {
	ParentExpression opOne;
	ASTType type;
  public ASTInstanceOfExpression(int id) {
    super(id);
  }

  public ASTInstanceOfExpression(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
