/* Generated By:JJTree: Do not edit this line. ASTInstanceArrayAllocation.java */

public class ASTInstanceArrayAllocation extends ParentExpression {
	ASTName name;
	ASTDimensionParameter dimensionParameter;
	
	String arrayClassName;
	int noOfDimension;
  public ASTInstanceArrayAllocation(int id) {
    super(id);
  }

  public ASTInstanceArrayAllocation(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
