/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpressionNode.java */

public class ASTInstanceOfExpressionNode extends SimpleNode {
  public ASTInstanceOfExpressionNode(int id) {
    super(id);
  }

  public ASTInstanceOfExpressionNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
