/* Generated By:JJTree: Do not edit this line. ASTImplementsClause.java */
import java.util.*;

public class ASTImplementsClause extends SimpleNode {
	ArrayList<String> interfaceList = new ArrayList<String>(); 
	
	ArrayList<ASTIdentifier> identifierList = new ArrayList<ASTIdentifier>();
  public ASTImplementsClause(int id) {
    super(id);
  }

  public ASTImplementsClause(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
