/* Generated By:JJTree: Do not edit this line. ASTInheritsClause.java */

public class ASTInheritsClause extends SimpleNode {
	ASTIdentifier identifier;
	String inheritsClassName;
  public ASTInheritsClause(int id) {
    super(id);
  }

  public ASTInheritsClause(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
