/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

public class ASTIdentifier extends SimpleNode {
	Token t;
	String idName ;
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
