/* Generated By:JJTree: Do not edit this line. ASTInterfaceMethodHeader.java */

public class ASTInterfaceMethodHeader extends SimpleNode {
	
	ASTReturnType returnType;
	ASTFormalParameters formalParameters;
	String interfaceMethodName ;
	String interfaceMethodSignature;
	String interfaceMethodReturnType;
	Token t;
	
	InterfaceMethod interfaceMethod;
  public ASTInterfaceMethodHeader(int id) {
    super(id);
  }

  public ASTInterfaceMethodHeader(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
