/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java */

public class ASTIfStatement extends ParentStatement {
	
	ASTExpression expression;
	ASTStatement thenPartStatement;
	ASTStatement elsePartStatement;
	
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
