/* Generated By:JJTree: Do not edit this line. ASTInterfaceBody.java */

import java.util.*;

public class ASTInterfaceBody extends SimpleNode {
	ArrayList<ASTInterfaceMethodDeclaration> interfaceMethodDeclarationList = new ArrayList<ASTInterfaceMethodDeclaration>();
  public ASTInterfaceBody(int id) {
    super(id);
  }

  public ASTInterfaceBody(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
