/* Generated By:JJTree: Do not edit this line. ASTInstanceAllocation.java */

public class ASTInstanceAllocation extends ParentExpression {
	ASTName name;
	ASTArguments arguments;
	
	String constructorClassName ;
	String constructorSignature;
	UCSYMethod constructorMethod;
  public ASTInstanceAllocation(int id) {
    super(id);
  }

  public ASTInstanceAllocation(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
