/* Generated By:JJTree: Do not edit this line. ASTIdentifierStarThisPrimaryPrefix.java */

public class ASTIdentifierStarThisPrimaryPrefix extends ParentExpression {
  public ASTIdentifierStarThisPrimaryPrefix(int id) {
    super(id);
  }

  public ASTIdentifierStarThisPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
