/* Generated By:JJTree: Do not edit this line. ASTInterfaceMethodDeclaration.java */

public class ASTInterfaceMethodDeclaration extends SimpleNode {
	ASTInterfaceMethodHeader interfaceMethodHeader;
  public ASTInterfaceMethodDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceMethodDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
