/* Generated By:JJTree: Do not edit this line. ASTLTNode.java */

public class ASTLTNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTLTNode(int id) {
    super(id);
  }

  public ASTLTNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
