/* Generated By:JJTree: Do not edit this line. ASTLiteralPrimaryPrefix.java */

public class ASTLiteralPrimaryPrefix extends ParentName {
	ParentExpression literalNode;
  public ASTLiteralPrimaryPrefix(int id) {
    super(id);
  }

  public ASTLiteralPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
