/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java */

import java.util.*;

public class ASTLocalVariableDeclaration extends ParentStatement {
	ASTType type;
	ArrayList<ASTVariableDeclarator> variableDeclaratorList = new ArrayList<ASTVariableDeclarator>();
  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
