/* Generated By:JJTree: Do not edit this line. ASTLongLiteral.java */

public class ASTLongLiteral extends ParentExpression {
	long value;
	Token t;
  public ASTLongLiteral(int id) {
    super(id);
  }

  public ASTLongLiteral(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
