/* Generated By:JJTree: Do not edit this line. ASTLTEqualNode.java */

public class ASTLTEqualNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTLTEqualNode(int id) {
    super(id);
  }

  public ASTLTEqualNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
