/* Generated By:JJTree: Do not edit this line. ASTMetaClassHeader.java */

public class ASTMetaClassHeader extends SimpleNode {
	Token t;
	Token parent;
	String metaClassName;
	String parentClassName;
	String defaultClassName;
	
  public ASTMetaClassHeader(int id) {
    super(id);
  }

  public ASTMetaClassHeader(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
