/* Generated By:JJTree: Do not edit this line. ASTMethodCallStatement.java */

public class ASTMethodCallStatement extends ParentStatement {
	
	ASTPrimaryExpression primaryExpression;
  public ASTMethodCallStatement(int id) {
    super(id);
  }

  public ASTMethodCallStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
