/* Generated By:JJTree: Do not edit this line. ASTMethodCall.java */

public class ASTMethodCall extends SimpleNode {
	Token t;
	String methodName;
	ASTArguments arguments;
	String methodSignature;
  public ASTMethodCall(int id) {
    super(id);
  }

  public ASTMethodCall(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
