/* Generated By:JJTree: Do not edit this line. ASTMetaInstanceType.java */

public class ASTMetaInstanceType extends SimpleNode {
	Token t;
	String metaInstanceTypeName;
	
  public ASTMetaInstanceType(int id) {
    super(id);
  }

  public ASTMetaInstanceType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
