/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java */

public class ASTMethodDeclaration extends MemberDeclaration {
	String methodName;
	int modifier;
	String methodSignature;
	String methodReturnType;
	String methodProtocol;
	ASTMethodHeader methodHeader;
	ASTBlock        block;
	UCSYMethod      method;
	
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
