/* Generated By:JJTree: Do not edit this line. ASTMetaClassDeclaration.java */

public class ASTMetaClassDeclaration extends ParentTypeDeclaration {
	ASTMetaClassHeader metaClassHeader;
	ASTMetaClassBody   metaClassBody;
	
	UCSYMetaClass theMetaClass;	
  public ASTMetaClassDeclaration(int id) {
    super(id);
  }

  public ASTMetaClassDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
