/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationLookAhead.java */

public class ASTMethodDeclarationLookAhead extends SimpleNode {
  public ASTMethodDeclarationLookAhead(int id) {
    super(id);
  }

  public ASTMethodDeclarationLookAhead(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
