/* Generated By:JJTree: Do not edit this line. ASTModulusNode.java */

public class ASTModulusNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTModulusNode(int id) {
    super(id);
  }

  public ASTModulusNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
