/* Generated By:JJTree: Do not edit this line. ASTMultiplyNode.java */

public class ASTMultiplyNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTMultiplyNode(int id) {
    super(id);
  }

  public ASTMultiplyNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
