/* Generated By:JJTree: Do not edit this line. ASTMethodHeader.java */
import java.util.*;

public class ASTMethodHeader extends SimpleNode {
	Token t;
	ArrayList<ASTMethodModifier> modifierList = new ArrayList<ASTMethodModifier>();
	ASTReturnType returnType;
	ASTFormalParameters formalParameters;
	String methodName;
	String methodSignature;
	String methodReturnType;
	int    methodAttribute;
	
  public ASTMethodHeader(int id) {
    super(id);
  }

  public ASTMethodHeader(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
