/* Generated By:JJTree: Do not edit this line. ASTMethodSignature.java */

public class ASTMethodSignature extends SimpleNode {
	Token t;
	String methodName;
	String methodSignature;
	String methodReturnType;
	ASTFormalParameters formalParameters;
  public ASTMethodSignature(int id) {
    super(id);
  }

  public ASTMethodSignature(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
