/* Generated By:JJTree: Do not edit this line. ASTMemberDeclaration.java */

public class ASTMemberDeclaration extends SimpleNode {
	
	int memberModifier;
	
	ASTAccessModifier accessModifier;
	
	/*ASTConstructorDeclaration constructorDeclaration ;
	ASTAbstractMethodDeclaration abstractMethodDeclaration;
	ASTMethodDeclaration methodDeclaration;
	ASTFieldDeclaration fieldDeclaration;
	ASTDelegateDeclaration delegateDeclaration;
	*/
	MemberDeclaration memberDeclaration;
  public ASTMemberDeclaration(int id) {
    super(id);
  }

  public ASTMemberDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
