/* Generated By:JJTree: Do not edit this line. ASTMetaClassBody.java */
import java.util.*;
public class ASTMetaClassBody extends SimpleNode {
	
	ArrayList<ASTAbstractConstructor> abstractConstructorList = new ArrayList<ASTAbstractConstructor>();
	ArrayList<ASTInterfaceMethodDeclaration> interfaceMethodDeclarationList = new ArrayList<ASTInterfaceMethodDeclaration>();
  public ASTMetaClassBody(int id) {
    super(id);
  }

  public ASTMetaClassBody(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
