/* Generated By:JJTree: Do not edit this line. ASTNamePrimaryPrefix.java */

public class ASTNamePrimaryPrefix extends ParentName {
	ASTName name;
  public ASTNamePrimaryPrefix(int id) {
    super(id);
  }

  public ASTNamePrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
