/* Generated By:JJTree: Do not edit this line. ASTNotNode.java */

public class ASTNotNode extends ParentExpression {
	ParentExpression opOne;
  public ASTNotNode(int id) {
    super(id);
  }

  public ASTNotNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
