/* Generated By:JJTree: Do not edit this line. ASTName.java */
import java.util.*;

public class ASTName extends ParentName {
	//ArrayList<String> nameList = new ArrayList<String>();
	Token t;
  public ASTName(int id) {
    super(id);
  }

  public ASTName(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  public String toString()
  {
  	return "ASTName";
  }
}
