/* Generated By:JJTree: Do not edit this line. ASTNotEqualNode.java */

public class ASTNotEqualNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTNotEqualNode(int id) {
    super(id);
  }

  public ASTNotEqualNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
