/* Generated By:JJTree: Do not edit this line. ASTPrimaryPrefix.java */

public class ASTPrimaryPrefix extends ParentName {
	ParentName primaryPrefix;
	
  public ASTPrimaryPrefix(int id) {
    super(id);
  }

  public ASTPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
