/* Generated By:JJTree: Do not edit this line. ASTPlusNode.java */

public class ASTPlusNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTPlusNode(int id) {
    super(id);
  }

  public ASTPlusNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
