/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java */

public class ASTPrimitiveType extends SimpleNode {
	Token t;
	int primitiveType;
	String typeName;
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
