/* Generated By:JJTree: Do not edit this line. ASTReturnType.java */

public class ASTReturnType extends SimpleNode {
	String typeName;
	ASTVoidType voidType;
	ASTType type;
  public ASTReturnType(int id) {
    super(id);
  }

  public ASTReturnType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
