/* Generated By:JJTree: Do not edit this line. ASTreportSSError.java */

public class ASTreportSSError extends SimpleNode {
  public ASTreportSSError(int id) {
    super(id);
  }

  public ASTreportSSError(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
