/* Generated By:JJTree: Do not edit this line. ASTReturnTypeDotClassPrimaryPrefix.java */

public class ASTReturnTypeDotClassPrimaryPrefix extends ParentExpression {
  public ASTReturnTypeDotClassPrimaryPrefix(int id) {
    super(id);
  }

  public ASTReturnTypeDotClassPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
