/* Generated By:JJTree: Do not edit this line. ASTReferenceType.java */

public class ASTReferenceType extends SimpleNode {
	
	ASTMetaInstanceType metaInstanceType;
	ASTArrayType arrayType;
	ASTClassType classType;
	
	String typeName;
  public ASTReferenceType(int id) {
    super(id);
  }

  public ASTReferenceType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
