/* Generated By:JJTree: Do not edit this line. ASTReturnStatement.java */

public class ASTReturnStatement extends ParentStatement {
	Token t;
	ASTExpression expression;
	String returnType;
  public ASTReturnStatement(int id) {
    super(id);
  }

  public ASTReturnStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
