/* Generated By:JJTree: Do not edit this line. ASTResultType.java */

public class ASTResultType extends SimpleNode {
	boolean voidType ;
	ASTType type;
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
