/* Generated By:JJTree: Do not edit this line. ASTRebindStatement.java */

public class ASTRebindStatement extends ParentStatement {
	
	Token rebindMethodNameToken;
	Token rebindClassToken;
	
	String rebindMethodName;//from RightHandSide
	String rebindClassName;//from RightHandSide
	//ASTPrimaryExpression sourceExpression;
	ASTName destinationExpression;
	UCSYMethod rebindMethod ;
	UCSYMethod targetMethod;
	String targetClassName;
  public ASTRebindStatement(int id) {
    super(id);
  }

  public ASTRebindStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
