/* Generated By:JJTree: Do not edit this line. ASTSignatureToCall.java */

public class ASTSignatureToCall extends SimpleNode {
	UCSYMethod method; //Compiler Generated Method for Interface
	UCSYMethod methodToCall; //to call actual method of class 
	ASTMethodSignature signature;//Signature is interface method in adapts clause
	
	ASTMethodCall      methodCall;

	DelegateClause delegateClause;	
	
	boolean isUsedByAdaptClause;
	
	//Following are used by adapted clause
	
	String adaptInterfaceName ;
	String adaptClassName;
  public ASTSignatureToCall(int id) {
    super(id);
  }

  public ASTSignatureToCall(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
