/* Generated By:JJTree: Do not edit this line. ASTSuffixDotIdentifierNode.java */

public class ASTSuffixDotIdentifierNode extends ParentName {
	String name;
	Token t;
  public ASTSuffixDotIdentifierNode(int id) {
    super(id);
  }

  public ASTSuffixDotIdentifierNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
