/* Generated By:JJTree: Do not edit this line. ASTSubtractNode.java */

public class ASTSubtractNode extends ParentExpression {
	ParentExpression opOne,opTwo;
  public ASTSubtractNode(int id) {
    super(id);
  }

  public ASTSubtractNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
