/* Generated By:JJTree: Do not edit this line. ASTStart.java */
import java.util.*;

public class ASTStart extends SimpleNode {

ArrayList<ASTTypeDeclaration> typeDeclaration = new ArrayList<ASTTypeDeclaration>();	
	
  public ASTStart(int id) {
    super(id);
  }
	
  public ASTStart(UCSY p, int id) {
    super(p, id);
  }

	void addTypeDeclaration(ASTTypeDeclaration d)
	{
		typeDeclaration.add( d );
	}
  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
