/* Generated By:JJTree: Do not edit this line. ASTSuperDotIdentifierPrimaryPrefix.java */

public class ASTSuperDotIdentifierPrimaryPrefix extends ParentExpression {
  public ASTSuperDotIdentifierPrimaryPrefix(int id) {
    super(id);
  }

  public ASTSuperDotIdentifierPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
