/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java */
import java.util.*;

public class ASTSwitchStatement extends ParentStatement {
	ArrayList caseValue = new ArrayList();
	ASTExpression expression;
	ArrayList<ASTCaseStatement> caseStatementList = new ArrayList<ASTCaseStatement>();
	ASTDefaultStatement defaultStatement;
	
	ArrayList<Integer> jumpFalseCodeIndex = new ArrayList<Integer>();
  public ASTSwitchStatement(int id) {
    super(id);
  }

  public ASTSwitchStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
