/* Generated By:JJTree: Do not edit this line. ASTsetCompileOutput.java */

public class ASTsetCompileOutput extends SimpleNode {
  public ASTsetCompileOutput(int id) {
    super(id);
  }

  public ASTsetCompileOutput(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
