/* Generated By:JJTree: Do not edit this line. ASTSuperPrimaryPrefix.java */

public class ASTSuperPrimaryPrefix extends ParentName {
	Token t;
  public ASTSuperPrimaryPrefix(int id) {
    super(id);
  }

  public ASTSuperPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
