/* Generated By:JJTree: Do not edit this line. ASTStatement.java */

public class ASTStatement extends SimpleNode {
	/*
	ASTAssignmentStatement         assignmentStatement;
	ASTLocalVariableDeclaration    localVariableDeclaration;
	ASTPrimaryExpression           primaryExpression;
	ASTBlock                       block;
	ASTEmptyStatement              emptyStatement;
	ASTSwitchStatement             switchStatement;
	ASTIfStatement                 ifStatement;
	ASTWhileStatement              whileStatement;
	ASTDoStatement                 doStatement;
	ASTForStatement                forStatement;
	ASTReturnStatement             returnStatement;
	ASTContinueStatement           continueStatement;
	ASTTryStatement                tryStatement;
	ASTThrowStatement              throwStatement;
	ASTRebindStatement             rebindStatement;
	*/
	ParentStatement pStatement;
  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
