/* Generated By:JJTree: Do not edit this line. ASTSuperNode.java */

public class ASTSuperNode extends SimpleNode {
  public ASTSuperNode(int id) {
    super(id);
  }

  public ASTSuperNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
