/* Generated By:JJTree: Do not edit this line. ASTThisPrimarySuffixNode.java */

public class ASTThisPrimarySuffixNode extends SimpleNode {
  public ASTThisPrimarySuffixNode(int id) {
    super(id);
  }

  public ASTThisPrimarySuffixNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
