/* Generated By:JJTree: Do not edit this line. ASTThisPrimaryPrefix.java */

public class ASTThisPrimaryPrefix extends ParentName {
	Token t;
  public ASTThisPrimaryPrefix(int id) {
    super(id);
  }

  public ASTThisPrimaryPrefix(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
