/* Generated By:JJTree: Do not edit this line. ASTTypeDeclaration.java */

public class ASTTypeDeclaration extends SimpleNode {
	ParentTypeDeclaration typeDeclaration;	
  public ASTTypeDeclaration(int id) {
    super(id);
  }

  public ASTTypeDeclaration(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
