/* Generated By:JJTree: Do not edit this line. ASTThisPrimaryPrefixNode.java */

public class ASTThisPrimaryPrefixNode extends SimpleNode {
  public ASTThisPrimaryPrefixNode(int id) {
    super(id);
  }

  public ASTThisPrimaryPrefixNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
