/* Generated By:JJTree: Do not edit this line. ASTUnaryMinusNode.java */

public class ASTUnaryMinusNode extends ParentExpression {
	ParentExpression opOne;
  public ASTUnaryMinusNode(int id) {
    super(id);
  }

  public ASTUnaryMinusNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
