/* Generated By:JJTree: Do not edit this line. ASTUniMinusNode.java */

public class ASTUniMinusNode extends ParentExpression {
	ParentExpression opOne;
  public ASTUniMinusNode(int id) {
    super(id);
  }

  public ASTUniMinusNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
