/* Generated By:JJTree: Do not edit this line. ASTUniPlusNode.java */

public class ASTUniPlusNode extends ParentExpression {
	ParentExpression opOne;
  public ASTUniPlusNode(int id) {
    super(id);
  }

  public ASTUniPlusNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
