/* Generated By:JJTree: Do not edit this line. ASTUnaryPlusNode.java */

public class ASTUnaryPlusNode extends ParentExpression {
	ParentExpression opOne;
  public ASTUnaryPlusNode(int id) {
    super(id);
  }

  public ASTUnaryPlusNode(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
