/* Generated By:JJTree: Do not edit this line. ASTVariableInitializer.java */

public class ASTVariableInitializer extends ParentExpression {
	ParentExpression expression;
	
  public ASTVariableInitializer(int id) {
    super(id);
  }

  public ASTVariableInitializer(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
