/* Generated By:JJTree: Do not edit this line. ASTWhileStatement.java */

public class ASTWhileStatement extends ParentStatement {
	ASTExpression expression;
	ASTStatement statement;
  public ASTWhileStatement(int id) {
    super(id);
  }

  public ASTWhileStatement(UCSY p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(UCSYVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
