/* Generated By:JJTree&JavaCC: Do not edit this line. UCSYConstants.java */
public interface UCSYConstants {

  int EOF = 0;
  int BOOLEAN = 6;
  int CHAR = 7;
  int INTEGER = 8;
  int FLOAT = 9;
  int DOUBLE = 10;
  int VOID = 11;
  int BYTE = 12;
  int SHORT = 13;
  int LONG = 14;
  int PUBLIC = 15;
  int PRIVATE = 16;
  int PROTECTED = 17;
  int INTERNAL = 18;
  int NATIVE = 19;
  int STATIC = 20;
  int DO = 21;
  int IF = 22;
  int ELSE = 23;
  int WHILE = 24;
  int FOR = 25;
  int TO = 26;
  int NEW = 27;
  int NULL = 28;
  int RETURN = 29;
  int BREAK = 30;
  int CONTIUNE = 31;
  int SWITCH = 32;
  int CASE = 33;
  int MYDEFAULT = 34;
  int STRING = 35;
  int TRUE = 36;
  int FALSE = 37;
  int AND = 38;
  int OR = 39;
  int Not = 40;
  int CLASS = 41;
  int TRY = 42;
  int CATCH = 43;
  int FINALLY = 44;
  int THROW = 45;
  int FINAL = 46;
  int SINGLETON = 47;
  int META = 48;
  int DELEGATE = 49;
  int FUNCTOR = 50;
  int CONFORMS = 51;
  int REBIND = 52;
  int REBINDABLE = 53;
  int MULTIDISPATCH = 54;
  int OVERRIDE = 55;
  int INTERFACE = 56;
  int IMPLEMENTS = 57;
  int ABSTRACT = 58;
  int ADAPTS = 59;
  int HANDLES = 60;
  int ALL = 61;
  int WITH = 62;
  int DECORATE = 63;
  int AFTER = 64;
  int BEFORE = 65;
  int INHERITS = 66;
  int INSTANCEOF = 67;
  int PACKAGE = 68;
  int IMPORT = 69;
  int FREE = 70;
  int OF = 71;
  int FORWARDS = 72;
  int MULTI = 73;
  int THIS = 74;
  int SUPER = 75;
  int EXECUTE = 76;
  int TIMES = 77;
  int IDENTIFIER = 78;
  int LEFTPARAN = 79;
  int RIGHTPARAN = 80;
  int GT = 81;
  int LT = 82;
  int GTE = 83;
  int LTE = 84;
  int EQUAL = 85;
  int NOTEQUAL = 86;
  int PLUS = 87;
  int MINUS = 88;
  int DIV = 89;
  int MOD = 90;
  int MUL = 91;
  int SEMICOLON = 92;
  int DOT = 93;
  int COLON = 94;
  int ASSIGN = 95;
  int PLUSASSIGN = 96;
  int MINUSASSIGN = 97;
  int MODASSIGN = 98;
  int DIVASSIGN = 99;
  int MULASSIGN = 100;
  int COMMA = 101;
  int AT = 102;
  int LBRACE = 103;
  int RBRACE = 104;
  int LBRACKET = 105;
  int RBRACKET = 106;
  int SINGLE_LINE_COMMENT = 107;
  int FORMAL_COMMENT = 108;
  int MULTI_LINE_COMMENT = 109;
  int INTEGERLITERAL = 110;
  int DECIMAL_LITERAL = 111;
  int FLOATLITERAL = 112;
  int DECIMAL_EXPONENT = 113;
  int CHARLITERAL = 114;
  int DOUBLELITERAL = 115;
  int LONGLITERAL = 116;
  int STRINGLITERAL = 117;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"boolean\"",
    "\"char\"",
    "\"int\"",
    "\"float\"",
    "\"double\"",
    "\"void\"",
    "\"byte\"",
    "\"short\"",
    "\"long\"",
    "\"public\"",
    "\"private\"",
    "\"protected\"",
    "\"internal\"",
    "\"native\"",
    "\"static\"",
    "\"do\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"to\"",
    "\"new\"",
    "\"null\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"string\"",
    "\"true\"",
    "\"false\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"class\"",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "\"throw\"",
    "\"final\"",
    "\"singleton\"",
    "\"meta\"",
    "\"delegate\"",
    "\"functor\"",
    "\"conforms\"",
    "\"rebind\"",
    "\"rebindable\"",
    "\"multidispatch\"",
    "\"override\"",
    "\"interface\"",
    "\"implements\"",
    "\"abstract\"",
    "\"adapts\"",
    "\"handles\"",
    "\"all\"",
    "\"with\"",
    "\"decorates\"",
    "\"after\"",
    "\"before\"",
    "\"inherits\"",
    "\"instanceof\"",
    "\"package\"",
    "\"import\"",
    "\"free\"",
    "\"of\"",
    "\"forwards\"",
    "\"multi\"",
    "\"this\"",
    "\"super\"",
    "\"execute\"",
    "\"times\"",
    "<IDENTIFIER>",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"*\"",
    "\";\"",
    "\".\"",
    "\":\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"%=\"",
    "\"/=\"",
    "\"*=\"",
    "\",\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<INTEGERLITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATLITERAL>",
    "<DECIMAL_EXPONENT>",
    "<CHARLITERAL>",
    "<DOUBLELITERAL>",
    "<LONGLITERAL>",
    "<STRINGLITERAL>",
    "\"!=\"",
  };

}
